# Generated by Django 5.0.3 on 2024-03-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Hod', 'Hod')], max_length=50, null=True),
        ),
    ]
